[package]
edition = "2021"
name = "chonkit"
version = "0.1.0"

[dependencies]
argon2 = "0.5.3"
async-recursion = "1.0.5"
axum = "0.7.4"
axum-extra = { version = "0.9.3", features = [
    "cookie",
    "typed-header",
    "cookie-private",
] }
axum-macros = "0.4.1"
base64 = "0.22.0"
chrono = { version = "0.4.33", features = ["serde"] }
clap = { version = "4.5.3", features = ["derive"] }
cookie = "0.18.1"
fastembed = "3.6.0"
hf-hub = { version = "0.3.2", features = ["tokio"] }
lazy_static = "1.4.0"
lopdf = { version = "0.33.0", features = ["async"] }
notify = "6.1.1"
qdrant-client = "1.10.1"
serde = "1.0.183"
serde_json = "1.0.114"
serde_yaml = "0.9.31"
sqlx = { version = "0.7.3", features = [
    "postgres",
    "chrono",
    "macros",
    "any",
    "runtime-tokio",
    "uuid",
] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
tonic = "0.11.0"
tower-http = { version = "0.5.0", features = [
    "fs",
    "tracing",
    "trace",
    "cors",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
validify = "1.3.0"
docx-rs = "0.4.17"
weaviate-community = "0.2.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
