# Same as docker-compose, but without the API.
name: chonkit
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chonkit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/docker/chonkit/postgres/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant_data:/var/lib/docker/chonkit/qdrant/data

volumes:
  postgres_data:
  qdrant_data:
